name: 'Trigger Evaluation'
description: 'Triggers the evaluation workflow on a specific branch.'

inputs:
  branch-name:
    description: 'The branch to run the evaluation on.'
    required: true
  is-release-dry-run:
    description: 'Whether the parent release workflow is a dry-run.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Trigger Evaluation'
      env:
        GH_TOKEN: ${{ github.token }}
      shell: 'bash'
      run: |
        # For the eval workflow, `dry-run` means "don't create an issue on failure".
        # We want to create issues for REAL releases, so we set `dry-run` to `false`
        # when the release is NOT a dry run.
        EVAL_DRY_RUN="true"
        if [[ "${{ inputs.is-release-dry-run }}" == "false" ]]; then
          EVAL_DRY_RUN="false"
        fi

        echo "Triggering evaluation for branch: ${{ inputs.branch-name }}"
        echo "Is release a dry run? ${{ inputs.is-release-dry-run }}"
        echo "Passing dry-run=${EVAL_DRY_RUN} to eval.yml"

        gh workflow run eval.yml --ref '${{ inputs.branch-name }}' \
          -f branch-or-commit='${{ inputs.branch-name }}' \
          -f dry-run=${EVAL_DRY_RUN}
